### PR TITLE
[WD-17923] split routes into several files

### PR DESCRIPTION
**Pull request by akbarkz**
## Done

Split routes defined in app.py into several files for better readability and maintainability

## QA

- Open the demo
- Check that everything works as expected

## Issue

Fixes https://warthogs.atlassian.net/browse/WD-17923

### CODE REVIEW

**Review by samhotep — COMMENTED** [review]
The code LGTM, however in the demo, selecting `canonical.com` brings a smaller tree than expected, compare:
demo:
image
production:
image

**Comment by akbarkz** [comment]
> The code LGTM, however in the demo, selecting `canonical.com` brings a smaller tree than expected

Please check again, cause I see identical trees in demo and production

**Comment by samhotep** [comment]
Works in incognito mode, probably something to do with my browser cache

**Review by samhotep — APPROVED** [review]
lgtm

**Pull request merged**
